# .gitee/workflows/build.yml
name: 构建Windows和Mac可执行程序

on:
  push:
    # tags:
    #   - 'v*'  # 当推送带v开头的tag时触发，例如v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install -r requirements.txt
          
      - name: 构建Windows可执行文件
        run: |
          # 优先使用spec文件打包
          if (Test-Path -Path "excel-app.spec") {
              pyinstaller --noconfirm excel-app.spec
          } else {
              # 如果spec文件不存在，使用命令行参数
              pyinstaller --onefile --windowed --name "Excel数据处理工具" excel_ui.py
          }
          
      - name: 上传构建结果
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/Excel数据处理工具.exe
  
  build-mac:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install -r requirements.txt
          
      - name: 构建Mac可执行文件 
        run: |
          # 优先使用spec文件打包
          if [ -f "excel-app.spec" ]; then
            pyinstaller --noconfirm excel-app.spec
          else
            # 如果spec文件不存在，使用命令行参数
            pyinstaller --onefile --windowed --name "Excel数据处理工具" excel_ui.py
          fi
          
      - name: 上传构建结果
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: dist/Excel数据处理工具

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v3
        with:
          path: ./builds
          
      - name: 创建Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./builds/windows-build/Excel数据处理工具.exe,./builds/mac-build/Excel数据处理工具"
          token: ${{ secrets.GITEE_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: 设置版本号
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        