# GitHub工作流配置
name: 构建Windows和Mac可执行程序

on:
  push:
    # 暂时允许所有推送都触发构建
    # tags:
    #   - 'v*'  # 当推送带v开头的tag时触发，例如v1.0.0
    
permissions:
  contents: write # 允许工作流创建release和上传文件

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install -r requirements.txt
          
      - name: 构建Windows可执行文件
        run: |
          # 优先使用spec文件打包
          if (Test-Path -Path "excel-app.spec") {
              pyinstaller --noconfirm excel-app.spec
          } else {
              # 如果spec文件不存在，使用命令行参数
              pyinstaller --onefile --windowed --name "报表小助手" excel_ui.py
          }
      
      # 将构建结果作为工作流产物上传
      - name: 上传Windows构建结果
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\报表小助手.exe
  
  build-mac:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install -r requirements.txt
          
      - name: 构建Mac可执行文件 
        run: |
          # 为Mac构建使用英文名称以避免编码问题
          if [ -f "excel-app.spec" ]; then
            # 修改spec文件中的名称
            sed -i '' 's/报表小助手/ExcelHelper/g' excel-app.spec
            pyinstaller --noconfirm excel-app.spec
          else
            # 使用英文名称构建
            pyinstaller --onefile --windowed --name "ExcelHelper" excel_ui.py
          fi
          
      - name: 创建Mac应用程序信息文件
        run: |
          # 创建Mac应用程序Info.plist以支持中文
          echo "创建Info.plist..."
          mkdir -p ExcelHelper.app/Contents
          cat > ExcelHelper.app/Contents/Info.plist << 'EOL'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleDisplayName</key>
            <string>报表小助手</string>
            <key>CFBundleExecutable</key>
            <string>ExcelHelper</string>
            <key>CFBundleIconFile</key>
            <string>icon-windowed.icns</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourcompany.excelhelper</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>报表小助手</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
          </dict>
          </plist>
          EOL
          
      - name: 设置Mac应用程序结构
        run: |
          # 复制可执行文件到应用程序包
          mkdir -p ExcelHelper.app/Contents/MacOS
          cp dist/ExcelHelper ExcelHelper.app/Contents/MacOS/ExcelHelper
      
      # 将构建结果作为工作流产物上传
      - name: 上传Mac构建结果
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: ExcelHelper.app
  
  # 如果是tag推送，创建Release
  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # 拉取代码
      - uses: actions/checkout@v3
      
      # 下载构建产物
      - name: 下载Windows构建产物
        uses: actions/download-artifact@v1
        with:
          name: windows-build
      
      - name: 下载Mac构建产物
        uses: actions/download-artifact@v1
        with:
          name: mac-build
      
      # 打包Mac应用为zip
      - name: 打包Mac应用
        run: |
          cd mac-build && zip -r ../报表小助手-Mac.zip . && cd ..
      
      # 创建Release并上传文件
      - name: 创建Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            报表小助手.exe
            报表小助手-Mac.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        